# Site settings
title: NemuriNemuri
email: ljsy2099@gmail.com
url: https://github.com/NemuriNemuri
description: "NemuriNemuri's Web Developer Portfolio! A dedicated and passionate web developer with 3.5 years of experience creating dynamic and responsive websites."
keywords: "Web Developer, Developer, Software Developer, NemuriNemuri"
skills: "Web Developer - Software Developer - Game Developer"
meta_author: NemuriNemuri

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: myshortname

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: FFE2E2 #80B3FF
  primary-rgb: "255,226,226" #"128,179,255"
  secondary: BAD7DF #FD6E8A
  secondary-dark: 99DDCC #A2122F
  text-color: BA7A7A

# Footer settings
footer:
  copyright: NemuriNemuri
  location: Location
  social: My Socials
  credits: References

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/NemuriNemuri1
  - title: facebook
    url: https://www.facebook.com/Nemmmuuuiii
  - title: youtube
    url: https://www.youtube.com/channel/UCTIz0SCtZP-fCv5DaiS9fsA
  - title: linkedin
    url: https://www.linkedin.com/in/lory-jyll-sy-573489288/
  - title: github
    url: http://github.com/NemuriNemuri

# Postal address (add as many lines as necessary)
address:
  - line: Cebu City, Cebu 6000, Philippines
  # - line: Philippines

# Credits content
credits: '
<ul class="list-inline">
  <li>Glaze Exclamador | Cyzennt Co. | 09466077501</li>
  <li>Karl Arboiz | Cyzennt Co. | 09300250061</li>
  <li>Christian Lloyd Remo | Cyzennt Co. | 09179860290</li>
  <li>Ara Salumbides | Kawaii Studios | 09225302664</li>
  <li>Kim Sanchez | Kawaii Studios | 09653893472</li>
</ul>'

# Build settings
markdown: kramdown
permalink: pretty

#for posts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: ""
